### ISSUE TITLE
Text Parse A1111 Embeddings doesn't find embeddings in extra_model_paths.yaml

### ISSUE THREAD

**Issue by AntitrustEnthusiast** [WASasquatch/was-node-suite-comfyui#130]
ComfyUI has a very useful feature to share model directories with A1111, saving huge amounts of disk space for large model collections.

example `extra_model_paths.yaml` placed in the root ComfyUI directory.
```yaml
a111:
    base_path: ~/dev/stable-diffusion-webui

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet
```

When you do this, ComfyUI will properly find embeddings in the stable-diffusion-webui directory. But the `Text Parse A1111 Embeddings` node doesn't seem to find them. It only works if I manually copy the embedding to the `ComfyUI/models/embeddings` directory.

If possible, please support this extra config option to avoid having to duplicate/hardlink embedding directories. Thanks!

### Steps to reproduce:

1. Add above yaml file in ComfyUI root directory as `extra_model_paths.yaml`, with correct value for `base_path`
2. Add 1 embedding to `stable-diffusion-webui/embeddings`, and a different embedding to `ComfyUI/models/embeddings`
3. Add both embedding names to `Text Parse A1111 Embeddings`
4. Generate

### Expected Results:
1. `Text Parse A1111 Embeddings` finds the embeddings in `ComfyUI/models/embeddings` and `stable-diffusion-webui/embeddings`

### Actual Results:
1. `Text Parse A1111 Embeddings` only finds embeddings in `ComfyUI/models/embeddings`
